import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/Navbar/page";
import Footer from "./_component/Footer/page";
import { Toaster } from "@/components/ui/toast";
import MyProvider from "./_component/MyProvider/MyProvider";
import { getCategory } from "@/Apis/apiCategory";
import { Providers } from "./_component/TanStackProvider/TanStack";

const exofont = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const categories = await getCategory();
  return (
    <html lang="en" className={exofont.className}>
      <body>
        <Providers>
        <MyProvider>
          <Navbar categories={categories}/>
          <div className="container mx-auto">
            {children}
            <Toaster />
          </div>
          <Footer />
        </MyProvider>
        </Providers>
      </body>
    </html>
  );
}